/**
 * The storefront catalogue: all 48 SKUs from the Aggregated Aggregates
 * pricing framework workbook, with every unit price pre-computed by the
 * pricing service's own calculators.
 *
 * pricing-framework.json is generated by
 * services/pricing/scripts/import_pricing_framework.py — never edit it by
 * hand. To change a price, change the workbook and re-run the script.
 */
import framework from "./pricing-framework.json";

export type Unit = "ton" | "m3" | "bag";
export type CustomerTierName = "RETAIL" | "CONTRACTOR_TRADE" | "VOLUME_CIVIL_BULK";
export type LoadSize = "M3_6" | "M3_10" | "M3_14_PLUS";

export type Product = {
  sku: string;
  slug: string;
  name: string;
  categorySlug: string;
  gradingStandard: string | null;
  unitOfSaleLabel: string;
  units: Unit[];
  bagWeightKg: number | null;
  bulkDensityKgPerM3: number;
  /** Unit price per tier, for the units the product is sold in. */
  prices: Record<CustomerTierName, Partial<Record<Unit, number>>>;
};

export type CustomerTier = {
  name: CustomerTierName;
  label: string;
  definition: string;
  discount: number;
  quoteOnlyMinM3: number | null;
};

export type DeliveryRules = {
  bands: { label: string; minKm: number; maxKm: number; fees: Partial<Record<LoadSize, number>> }[];
  quoteOverKm: number;
  minBulkM3: number;
  minBulkTons: number;
  smallLoadFee: number;
  smallLoadMaxKm: number;
  baggedFee: number;
  baggedMaxKm: number;
  baggedFreeFromKg: number;
};

export const PRODUCTS: Product[] = framework.products.map((p) => ({
  sku: p.sku,
  slug: p.slug,
  name: p.name,
  categorySlug: p.category_slug,
  gradingStandard: p.grading_standard,
  unitOfSaleLabel: p.unit_of_sale_label,
  units: p.units as Unit[],
  bagWeightKg: p.bag_weight_kg,
  bulkDensityKgPerM3: p.bulk_density_kg_per_m3,
  prices: p.prices as Product["prices"],
}));

export const CUSTOMER_TIERS: CustomerTier[] = framework.customer_tiers.map((t) => ({
  name: t.name as CustomerTierName,
  label: t.label,
  definition: t.definition,
  discount: t.discount,
  quoteOnlyMinM3: t.quote_only_min_m3,
}));

const d = framework.delivery;
export const DELIVERY_RULES: DeliveryRules = {
  bands: d.bands.map((b) => ({ label: b.label, minKm: b.min_km, maxKm: b.max_km, fees: b.fees })),
  quoteOverKm: d.quote_over_km,
  minBulkM3: d.min_bulk_m3,
  minBulkTons: d.min_bulk_tons,
  smallLoadFee: d.small_load_fee,
  smallLoadMaxKm: d.small_load_max_km,
  baggedFee: d.bagged_fee,
  baggedMaxKm: d.bagged_max_km,
  baggedFreeFromKg: d.bagged_free_from_kg,
};

export const PRICING_SOURCE = framework.source;

export function findProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
