"""
Loads data/pricing_framework.json — the machine-readable copy of the
Aggregated Aggregates pricing framework workbook — into calculator inputs.

That JSON is generated by scripts/import_pricing_framework.py from
docs/pricing/aggregated-aggregates-pricing-framework.xlsx and must never be
edited by hand (AGENTIC_RULES.md rule 1). The calculators only ever read the
workbook's inputs (base cost, markup, density, bag premium, tier discounts,
delivery charges); every price is derived from them at request time.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import Optional

from calculators.delivery_bands import DeliveryBand, DeliveryRules
from calculators.tonnage_volume import ProductPricing

DATA_PATH = Path(__file__).parent / "data" / "pricing_framework.json"


@dataclass(frozen=True)
class CustomerTier:
    name: str
    label: str
    discount: Decimal  # fraction
    quote_only_min_m3: Optional[Decimal]
    requires_po_invoice: bool


@dataclass(frozen=True)
class PricingFramework:
    raw: dict
    products: dict[str, ProductPricing]
    tiers: dict[str, CustomerTier]
    delivery: DeliveryRules


def _dec(value) -> Optional[Decimal]:
    return None if value is None else Decimal(str(value))


def build(raw: dict) -> PricingFramework:
    categories = {c["slug"]: c for c in raw["categories"]}

    products: dict[str, ProductPricing] = {}
    for p in raw["products"]:
        category = categories[p["category_slug"]]
        bagged = p["bag_weight_kg"] is not None
        products[p["sku"]] = ProductPricing(
            sku=p["sku"],
            name=p["name"],
            bulk_density_kg_per_m3=_dec(category["bulk_density_kg_per_m3"]),
            base_cost_per_ton=_dec(category["base_cost_per_ton"]),
            markup=_dec(category["markup"]),
            units=tuple(p["units"]),
            bag_premium_multiplier=_dec(category["bag_premium_multiplier"]) if bagged else None,
            bag_weight_kg=_dec(p["bag_weight_kg"]),
        )

    tiers = {
        t["name"]: CustomerTier(
            name=t["name"],
            label=t["label"],
            discount=_dec(t["discount"]),
            quote_only_min_m3=_dec(t["quote_only_min_m3"]),
            requires_po_invoice=t["requires_po_invoice"],
        )
        for t in raw["customer_tiers"]
    }

    d = raw["delivery"]
    delivery = DeliveryRules(
        bands=tuple(
            DeliveryBand(
                label=b["label"],
                min_km=_dec(b["min_km"]),
                max_km=_dec(b["max_km"]),
                fees={size: _dec(fee) for size, fee in b["fees"].items()},
            )
            for b in d["bands"]
        ),
        quote_over_km=_dec(d["quote_over_km"]),
        min_bulk_m3=_dec(d["min_bulk_m3"]),
        min_bulk_tons=_dec(d["min_bulk_tons"]),
        small_load_fee=_dec(d["small_load_fee"]),
        small_load_max_km=_dec(d["small_load_max_km"]),
        bagged_fee=_dec(d["bagged_fee"]),
        bagged_max_km=_dec(d["bagged_max_km"]),
        bagged_free_from_kg=_dec(d["bagged_free_from_kg"]),
    )

    return PricingFramework(raw=raw, products=products, tiers=tiers, delivery=delivery)


def load(path: Path = DATA_PATH) -> PricingFramework:
    with open(path) as f:
        return build(json.load(f))
